FROM alpine:latest
LABEL maintainer "baumhoto <baumhoto@gmail.com>"

# base container used for figuring out the steps to build software from source in alpine

RUN apk --no-cache add \
	build-base \
	git \
	vim \
	bash 

CMD bash -C

ENTRYPOINT [ "" ]
